# Generated by Django 3.1 on 2022-03-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='geography.place')),
            ],
        ),
        migrations.CreateModel(
            name='BusShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start of the shift')),
                ('end', models.DateTimeField(verbose_name='End of the shift')),
                ('bus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='fleet.bus')),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='fleet.driver')),
                ('stops', models.ManyToManyField(related_name='stops', to='shift.BusStop')),
            ],
        ),
    ]
